#!/usr/bin/env python3
"""
Project-specific PreToolUse hook for file edit commands.

Blocks manual edits to generated files in this repository.
Exit codes: 0=Allow, 2=Block
"""

from __future__ import annotations

from pathlib import Path

from custom_hooks import load_input, block, allow


BLOCKED_RELATIVE_PATHS = {
    "homebrew-tap/Formula/cld-gateway.rb": (
        "BLOCKED: homebrew-tap/Formula/cld-gateway.rb is auto-generated.\n\n"
        "Do not edit this file manually.\n"
        "Edit the source-of-truth template/rendering inputs instead."
    ),
}


def main() -> None:
    data = load_input()
    tool_input = data.get("tool_input", {})
    file_path = tool_input.get("file_path", "")

    if not file_path:
        allow()

    try:
        abs_path = Path(file_path).resolve()
        repo_root = Path.cwd().resolve()
        rel_path = abs_path.relative_to(repo_root).as_posix()
    except Exception:
        allow()

    if rel_path in BLOCKED_RELATIVE_PATHS:
        block(BLOCKED_RELATIVE_PATHS[rel_path])

    allow()


if __name__ == "__main__":
    main()
