[package]
name = "gatewayd"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
gateway-http-anthropic = { path = "../gateway-http-anthropic" }
gateway-observability = { path = "../gateway-observability" }
gateway-auth-codex = { path = "../gateway-auth-codex" }
axum.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
crossterm.workspace = true
ratatui.workspace = true

[[bin]]
name = "cld-gateway"
path = "src/main.rs"
